# TODO: Add your project title here
title: Python Poetry WSL2-Ubuntu-GPU Docker Template
description: This template sets up a Docker-based development environment for Python projects using Poetry with GPU support, specifically tailored for PyTorch. It works well on both Windows WSL2-Ubuntu and Ubuntu, and includes Jekyll for GitHub Pages documentation.
favicon_ico: "/assets/images/tareks_dog_willy.ico"

# TODO: Add your repository name here and select corresponding way to link it 
# on `gh-pages`, set like this:
# baseurl: "python-poetry-wsl2-ubuntu-gpu-docker-template" 
# url: https://github.com/liuyuweitarek/

# on `local jekyll server`, set like this: 
baseurl: ""
url: "https://localhost"


github: [metadata]
exclude: 
  - "Dockerfile"
  - "jekyll-doc-web.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - ".dockerignore"
  - ".gitignore"
  - ".editorconfig"

remote_theme: just-the-docs/just-the-docs@v0.8.1
color_scheme: tarek

# # Define Jekyll collections
# collections:
#   getting_started:
#     permalink: "./:collection/:path/"
#     output: true
#   documentations:
#     permalink: "./:collection/:path/"
#     output: true

# just_the_docs:
  # Define which collections are used in just-the-docs
  # collections:
    # Reference the "tests" collection
    # getting_started:
      # Give the collection a name
      # name: "Getting Started"
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: False
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: false
    # documentations:
      # name: Edit Docs
      # nav_fold: true 
      # nav_exclude: false 
      # search_exclude: false

incremental: true

callouts_level: quiet # or loud
callouts:
  images:
    color: purple
    opacity: 0.1
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: purple
  information:
    title: Information
    color: yellow
  warning:
    title: Warning
    color: red

# TODO: Add your repository info here
nav_external_links:
  - title: Source Code
    url: https://github.com/liuyuweitarek/python-poetry-wsl2-ubuntu-gpu-docker-template/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# TODO: Add your repository info here
# Aux links for the upper right navigation
aux_links:
  "View On Github":
    - https://github.com/liuyuweitarek/python-poetry-wsl2-ubuntu-gpu-docker-template/

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# TODO: Add your repository info here
footer_content:
  -  Found an error? Feel free to file a <a href="https://github.com/liuyuweitarek/python-poetry-wsl2-ubuntu-gpu-docker-template/issues">GitHub Issue</a>. :)

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."

#  TODO: Add your repository url here
gh_edit_repository: https://github.com/liuyuweitarek/python-poetry-wsl2-ubuntu-gpu-docker-template # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
